[build]
  command = "echo NEXT_PUBLIC_SHA=$COMMIT_REF >> .env.local && \
  yarn next build && yarn next export && \
  npx rollbar-cli upload-sourcemaps ./out \
    --access-token $ROLLBAR_SERVER_ACCESS_TOKEN \
    --code-version $COMMIT_REF \
    --url-prefix 'https://nostalgic-leavitt-673da8.netlify.app/' \
    --next"
  publish = "out"
