[onPreBuild]
  command = "echo NEXT_PUBLIC_SHA=$COMMIT_REF >> .env.local"

[onPostBuild]
  command = "npm install -g rollbar-cli && \
  rollbar-cli upload-sourcemaps ./out \
    --access-token $ROLLBAR_SERVER_ACCESS_TOKEN \
    --code-version $COMMIT_REF \
    --url-prefix 'https://app.rollbar.com/' \
    --next"

[build]
  command = "yarn next build && yarn next export"
  publish = "out"
