[build]
  command = "echo NEXT_PUBLIC_SHA=$COMMIT_REF >> .env.local && \
             yarn next build && yarn next export && \
             npm install -g rollbar-cli && \
             rollbar-cli upload-sourcemaps ./out \
               --access-token $ROLLBAR_SERVER_SIDE_ACCESS_TOKEN \
               --code-version $COMMIT_REF \
               --url-prefix 'https://app.rollbar.com/'"
  publish = "out"
